INSERT INTO users (name, zipcode)
VALUES ("Alec", 19146),
        ("Ben Franklin", 19103),
        ("Will Smith", 19119);

INSERT INTO surveys (user_id, question1, question2, question3, question4, question5, question6, question7, question8, question9, question10, question11, question12, question13)
VALUES (1, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1),
        (2, 1, 2, 3, 1, 2, 2, 2, 2, 3, 1, 2, 3, 1),
        (3, 1, 2, 3, 1, 2, 2, 2, 2, 3, 1, 2, 3, 1);  

INSERT INTO breed_matches (user_id, survey_id, breed_id)
VALUES (1, 1, 1),
        (1, 1, 2),
        (1, 1, 3), 
        (2, 2, 4),
        (2, 2, 5);             

INSERT INTO breeds (breed_name, attribute, score) 
VALUES
    ('affenpinscher','Adapts Well to Apartment Living',5),
    ('affenpinscher','Good For Novice Owners',4),
    ('affenpinscher','Sensitivity Level',3),
    ('affenpinscher','Tolerates Being Alone',1),
    ('affenpinscher','Affectionate with Family',5),
    ('affenpinscher','Incredibly Kid Friendly Dogs',1),
    ('affenpinscher','Dog Friendly',4),
    ('affenpinscher','Amount Of Shedding',1),
    ('affenpinscher','Size',1),
    ('affenpinscher','Easy To Train',2),
    ('affenpinscher','Energy Level',4),
    ('affenpinscher','Exercise Needs',3),
    ('afghan hound','Adapts Well to Apartment Living',5),
    ('afghan hound','Good For Novice Owners',3),
    ('afghan hound','Sensitivity Level',5),
    ('afghan hound','Tolerates Being Alone',2),
    ('afghan hound','Affectionate with Family',5),
    ('afghan hound','Incredibly Kid Friendly Dogs',5),
    ('afghan hound','Dog Friendly',4),
    ('afghan hound','Amount Of Shedding',4),
    ('afghan hound','Size',4),
    ('afghan hound','Easy To Train',1),
    ('afghan hound','Energy Level',5),
    ('afghan hound','Exercise Needs',4),
    ('akita','Adapts Well to Apartment Living',2),
    ('akita','Good For Novice Owners',2),
    ('akita','Sensitivity Level',5),
    ('akita','Tolerates Being Alone',1),
    ('akita','Affectionate with Family',5),
    ('akita','Incredibly Kid Friendly Dogs',1),
    ('akita','Dog Friendly',1),
    ('akita','Amount Of Shedding',5),
    ('akita','Size',4),
    ('akita','Easy To Train',2),
    ('akita','Energy Level',4),
    ('akita','Exercise Needs',4),
    ('alaskan malamute','Adapts Well to Apartment Living',1),
    ('alaskan malamute','Good For Novice Owners',1),
    ('alaskan malamute','Sensitivity Level',4),
    ('alaskan malamute','Tolerates Being Alone',1),
    ('alaskan malamute','Affectionate with Family',4),
    ('alaskan malamute','Incredibly Kid Friendly Dogs',3),
    ('alaskan malamute','Dog Friendly',2),
    ('alaskan malamute','Amount Of Shedding',5),
    ('alaskan malamute','Size',4),
    ('alaskan malamute','Easy To Train',4),
    ('alaskan malamute','Energy Level',5),
    ('alaskan malamute','Exercise Needs',5),
    ('american bulldog','Adapts Well to Apartment Living',1),
    ('american bulldog','Good For Novice Owners',1),
    ('american bulldog','Sensitivity Level',4),
    ('american bulldog','Tolerates Being Alone',1),
    ('american bulldog','Affectionate with Family',5),
    ('american bulldog','Incredibly Kid Friendly Dogs',4),
    ('american bulldog','Dog Friendly',2),
    ('american bulldog','Amount Of Shedding',1),
    ('american bulldog','Size',4),
    ('american bulldog','Easy To Train',4),
    ('american bulldog','Energy Level',4),
    ('american bulldog','Exercise Needs',4),
    ('american eskimo dog','Adapts Well to Apartment Living',5),
    ('american eskimo dog','Good For Novice Owners',4),
    ('american eskimo dog','Sensitivity Level',4),
    ('american eskimo dog','Tolerates Being Alone',2),
    ('american eskimo dog','Affectionate with Family',5),
    ('american eskimo dog','Incredibly Kid Friendly Dogs',5),
    ('american eskimo dog','Dog Friendly',5),
    ('american eskimo dog','Amount Of Shedding',5),
    ('american eskimo dog','Size',2),
    ('american eskimo dog','Easy To Train',5),
    ('american eskimo dog','Energy Level',5),
    ('american eskimo dog','Exercise Needs',4),
    ('american foxhound','Adapts Well to Apartment Living',1),
    ('american foxhound','Good For Novice Owners',2),
    ('american foxhound','Sensitivity Level',2),
    ('american foxhound','Tolerates Being Alone',1),
    ('american foxhound','Affectionate with Family',4),
    ('american foxhound','Incredibly Kid Friendly Dogs',5),
    ('american foxhound','Dog Friendly',5),
    ('american foxhound','Amount Of Shedding',3),
    ('american foxhound','Size',3),
    ('american foxhound','Easy To Train',2),
    ('american foxhound','Energy Level',5),
    ('american foxhound','Exercise Needs',5),
    ('american pit bull terrier','Adapts Well to Apartment Living',3),
    ('american pit bull terrier','Good For Novice Owners',2),
    ('american pit bull terrier','Sensitivity Level',4),
    ('american pit bull terrier','Tolerates Being Alone',1),
    ('american pit bull terrier','Affectionate with Family',5),
    ('american pit bull terrier','Incredibly Kid Friendly Dogs',5),
    ('american pit bull terrier','Dog Friendly',1),
    ('american pit bull terrier','Amount Of Shedding',4),
    ('american pit bull terrier','Size',3),
    ('american pit bull terrier','Easy To Train',4),
    ('american pit bull terrier','Energy Level',4),
    ('american pit bull terrier','Exercise Needs',4),
    ('american staffordshire terrier','Adapts Well to Apartment Living',2),
    ('american staffordshire terrier','Good For Novice Owners',2),
    ('american staffordshire terrier','Sensitivity Level',3),
    ('american staffordshire terrier','Tolerates Being Alone',2),
    ('american staffordshire terrier','Affectionate with Family',4),
    ('american staffordshire terrier','Incredibly Kid Friendly Dogs',4),
    ('american staffordshire terrier','Dog Friendly',2),
    ('american staffordshire terrier','Amount Of Shedding',2),
    ('american staffordshire terrier','Size',3),
    ('american staffordshire terrier','Easy To Train',4),
    ('american staffordshire terrier','Energy Level',3),
    ('american staffordshire terrier','Exercise Needs',3),
    ('australian cattle dog','Adapts Well to Apartment Living',2),
    ('australian cattle dog','Good For Novice Owners',1),
    ('australian cattle dog','Sensitivity Level',4),
    ('australian cattle dog','Tolerates Being Alone',3),
    ('australian cattle dog','Affectionate with Family',5),
    ('australian cattle dog','Incredibly Kid Friendly Dogs',3),
    ('australian cattle dog','Dog Friendly',4),
    ('australian cattle dog','Amount Of Shedding',3),
    ('australian cattle dog','Size',3),
    ('australian cattle dog','Easy To Train',5),
    ('australian cattle dog','Energy Level',5),
    ('australian cattle dog','Exercise Needs',5),
    ('australian kelpie','Adapts Well to Apartment Living',2),
    ('australian kelpie','Good For Novice Owners',2),
    ('australian kelpie','Sensitivity Level',4),
    ('australian kelpie','Tolerates Being Alone',2),
    ('australian kelpie','Affectionate with Family',4),
    ('australian kelpie','Incredibly Kid Friendly Dogs',2),
    ('australian kelpie','Dog Friendly',3),
    ('australian kelpie','Amount Of Shedding',3),
    ('australian kelpie','Size',3),
    ('australian kelpie','Easy To Train',5),
    ('australian kelpie','Energy Level',5),
    ('australian kelpie','Exercise Needs',5),
    ('australian shepherd','Adapts Well to Apartment Living',1),
    ('australian shepherd','Good For Novice Owners',2),
    ('australian shepherd','Sensitivity Level',5),
    ('australian shepherd','Tolerates Being Alone',2),
    ('australian shepherd','Affectionate with Family',5),
    ('australian shepherd','Incredibly Kid Friendly Dogs',4),
    ('australian shepherd','Dog Friendly',5),
    ('australian shepherd','Amount Of Shedding',3),
    ('australian shepherd','Size',3),
    ('australian shepherd','Easy To Train',5),
    ('australian shepherd','Energy Level',5),
    ('australian shepherd','Exercise Needs',5),
    ('australian terrier','Adapts Well to Apartment Living',5),
    ('australian terrier','Good For Novice Owners',3),
    ('australian terrier','Sensitivity Level',2),
    ('australian terrier','Tolerates Being Alone',2),
    ('australian terrier','Affectionate with Family',4),
    ('australian terrier','Incredibly Kid Friendly Dogs',3),
    ('australian terrier','Dog Friendly',2),
    ('australian terrier','Amount Of Shedding',1),
    ('australian terrier','Size',1),
    ('australian terrier','Easy To Train',3),
    ('australian terrier','Energy Level',5),
    ('australian terrier','Exercise Needs',4),
    ('basenji','Adapts Well to Apartment Living',5),
    ('basenji','Good For Novice Owners',4),
    ('basenji','Sensitivity Level',3),
    ('basenji','Tolerates Being Alone',4),
    ('basenji','Affectionate with Family',5),
    ('basenji','Incredibly Kid Friendly Dogs',5),
    ('basenji','Dog Friendly',4),
    ('basenji','Amount Of Shedding',1),
    ('basenji','Size',2),
    ('basenji','Easy To Train',1),
    ('basenji','Energy Level',5),
    ('basenji','Exercise Needs',5),
    ('basset hound','Adapts Well to Apartment Living',5),
    ('basset hound','Good For Novice Owners',4),
    ('basset hound','Sensitivity Level',4),
    ('basset hound','Tolerates Being Alone',3),
    ('basset hound','Affectionate with Family',5),
    ('basset hound','Incredibly Kid Friendly Dogs',5),
    ('basset hound','Dog Friendly',5),
    ('basset hound','Amount Of Shedding',4),
    ('basset hound','Size',2),
    ('basset hound','Easy To Train',2),
    ('basset hound','Energy Level',2),
    ('basset hound','Exercise Needs',2),
    ('beagle','Adapts Well to Apartment Living',4),
    ('beagle','Good For Novice Owners',3),
    ('beagle','Sensitivity Level',4),
    ('beagle','Tolerates Being Alone',1),
    ('beagle','Affectionate with Family',5),
    ('beagle','Incredibly Kid Friendly Dogs',5),
    ('beagle','Dog Friendly',5),
    ('beagle','Amount Of Shedding',3),
    ('beagle','Size',2),
    ('beagle','Easy To Train',1),
    ('beagle','Energy Level',4),
    ('beagle','Exercise Needs',4),
    ('bearded collie','Adapts Well to Apartment Living',3),
    ('bearded collie','Good For Novice Owners',4),
    ('bearded collie','Sensitivity Level',4),
    ('bearded collie','Tolerates Being Alone',2),
    ('bearded collie','Affectionate with Family',5),
    ('bearded collie','Incredibly Kid Friendly Dogs',4),
    ('bearded collie','Dog Friendly',5),
    ('bearded collie','Amount Of Shedding',4),
    ('bearded collie','Size',3),
    ('bearded collie','Easy To Train',5),
    ('bearded collie','Energy Level',4),
    ('bearded collie','Exercise Needs',4),
    ('bernese mountain dog','Adapts Well to Apartment Living',1),
    ('bernese mountain dog','Good For Novice Owners',2),
    ('bernese mountain dog','Sensitivity Level',4),
    ('bernese mountain dog','Tolerates Being Alone',1),
    ('bernese mountain dog','Affectionate with Family',5),
    ('bernese mountain dog','Incredibly Kid Friendly Dogs',5),
    ('bernese mountain dog','Dog Friendly',3),
    ('bernese mountain dog','Amount Of Shedding',5),
    ('bernese mountain dog','Size',5),
    ('bernese mountain dog','Easy To Train',4),
    ('bernese mountain dog','Energy Level',4),
    ('bernese mountain dog','Exercise Needs',3),
    ('bichon frise','Adapts Well to Apartment Living',5),
    ('bichon frise','Good For Novice Owners',5),
    ('bichon frise','Sensitivity Level',5),
    ('bichon frise','Tolerates Being Alone',1),
    ('bichon frise','Affectionate with Family',5),
    ('bichon frise','Incredibly Kid Friendly Dogs',4),
    ('bichon frise','Dog Friendly',4),
    ('bichon frise','Amount Of Shedding',2),
    ('bichon frise','Size',2),
    ('bichon frise','Easy To Train',5),
    ('bichon frise','Energy Level',5),
    ('bichon frise','Exercise Needs',3),
    ('black and tan coonhound','Adapts Well to Apartment Living',1),
    ('black and tan coonhound','Good For Novice Owners',2),
    ('black and tan coonhound','Sensitivity Level',3),
    ('black and tan coonhound','Tolerates Being Alone',2),
    ('black and tan coonhound','Affectionate with Family',5),
    ('black and tan coonhound','Incredibly Kid Friendly Dogs',5),
    ('black and tan coonhound','Dog Friendly',5),
    ('black and tan coonhound','Amount Of Shedding',5),
    ('black and tan coonhound','Size',3),
    ('black and tan coonhound','Easy To Train',2),
    ('black and tan coonhound','Energy Level',5),
    ('black and tan coonhound','Exercise Needs',5),
    ('black mouth cur','Adapts Well to Apartment Living',1),
    ('black mouth cur','Good For Novice Owners',2),
    ('black mouth cur','Sensitivity Level',4),
    ('black mouth cur','Tolerates Being Alone',2),
    ('black mouth cur','Affectionate with Family',5),
    ('black mouth cur','Incredibly Kid Friendly Dogs',5),
    ('black mouth cur','Dog Friendly',3),
    ('black mouth cur','Amount Of Shedding',3),
    ('black mouth cur','Size',4),
    ('black mouth cur','Easy To Train',3);
INSERT INTO breeds VALUES
    ('black mouth cur','Energy Level',4),
    ('black mouth cur','Exercise Needs',5),
    ('bloodhound','Adapts Well to Apartment Living',1),
    ('bloodhound','Good For Novice Owners',2),
    ('bloodhound','Sensitivity Level',4),
    ('bloodhound','Tolerates Being Alone',2),
    ('bloodhound','Affectionate with Family',5),
    ('bloodhound','Incredibly Kid Friendly Dogs',5),
    ('bloodhound','Dog Friendly',5),
    ('bloodhound','Amount Of Shedding',4),
    ('bloodhound','Size',4),
    ('bloodhound','Easy To Train',3),
    ('bloodhound','Energy Level',5),
    ('bloodhound','Exercise Needs',5),
    ('bluetick coonhound','Adapts Well to Apartment Living',2),
    ('bluetick coonhound','Good For Novice Owners',2),
    ('bluetick coonhound','Sensitivity Level',5),
    ('bluetick coonhound','Tolerates Being Alone',2),
    ('bluetick coonhound','Affectionate with Family',5),
    ('bluetick coonhound','Incredibly Kid Friendly Dogs',5),
    ('bluetick coonhound','Dog Friendly',3),
    ('bluetick coonhound','Amount Of Shedding',2),
    ('bluetick coonhound','Size',3),
    ('bluetick coonhound','Easy To Train',2),
    ('bluetick coonhound','Energy Level',5),
    ('bluetick coonhound','Exercise Needs',5),
    ('boerboel','Adapts Well to Apartment Living',1),
    ('boerboel','Good For Novice Owners',1),
    ('boerboel','Sensitivity Level',3),
    ('boerboel','Tolerates Being Alone',2),
    ('boerboel','Affectionate with Family',4),
    ('boerboel','Incredibly Kid Friendly Dogs',4),
    ('boerboel','Dog Friendly',2),
    ('boerboel','Amount Of Shedding',3),
    ('boerboel','Size',5),
    ('boerboel','Easy To Train',2),
    ('boerboel','Energy Level',3),
    ('boerboel','Exercise Needs',4),
    ('bolognese','Adapts Well to Apartment Living',5),
    ('bolognese','Good For Novice Owners',3),
    ('bolognese','Sensitivity Level',5),
    ('bolognese','Tolerates Being Alone',2),
    ('bolognese','Affectionate with Family',5),
    ('bolognese','Incredibly Kid Friendly Dogs',5),
    ('bolognese','Dog Friendly',5),
    ('bolognese','Amount Of Shedding',1),
    ('bolognese','Size',1),
    ('bolognese','Easy To Train',5),
    ('bolognese','Energy Level',3),
    ('bolognese','Exercise Needs',4),
    ('border collie','Adapts Well to Apartment Living',2),
    ('border collie','Good For Novice Owners',2),
    ('border collie','Sensitivity Level',5),
    ('border collie','Tolerates Being Alone',1),
    ('border collie','Affectionate with Family',5),
    ('border collie','Incredibly Kid Friendly Dogs',4),
    ('border collie','Dog Friendly',3),
    ('border collie','Amount Of Shedding',3),
    ('border collie','Size',3),
    ('border collie','Easy To Train',5),
    ('border collie','Energy Level',5),
    ('border collie','Exercise Needs',5),
    ('border terrier','Adapts Well to Apartment Living',4),
    ('border terrier','Good For Novice Owners',3),
    ('border terrier','Sensitivity Level',3),
    ('border terrier','Tolerates Being Alone',1),
    ('border terrier','Affectionate with Family',5),
    ('border terrier','Incredibly Kid Friendly Dogs',4),
    ('border terrier','Dog Friendly',2),
    ('border terrier','Amount Of Shedding',3),
    ('border terrier','Size',2),
    ('border terrier','Easy To Train',3),
    ('border terrier','Energy Level',4),
    ('border terrier','Exercise Needs',5),
    ('boston terrier','Adapts Well to Apartment Living',5),
    ('boston terrier','Good For Novice Owners',4),
    ('boston terrier','Sensitivity Level',5),
    ('boston terrier','Tolerates Being Alone',3),
    ('boston terrier','Affectionate with Family',4),
    ('boston terrier','Incredibly Kid Friendly Dogs',5),
    ('boston terrier','Dog Friendly',5),
    ('boston terrier','Amount Of Shedding',2),
    ('boston terrier','Size',2),
    ('boston terrier','Easy To Train',4),
    ('boston terrier','Energy Level',4),
    ('boston terrier','Exercise Needs',4),
    ('boxer','Adapts Well to Apartment Living',4),
    ('boxer','Good For Novice Owners',3),
    ('boxer','Sensitivity Level',4),
    ('boxer','Tolerates Being Alone',1),
    ('boxer','Affectionate with Family',5),
    ('boxer','Incredibly Kid Friendly Dogs',4),
    ('boxer','Dog Friendly',3),
    ('boxer','Amount Of Shedding',4),
    ('boxer','Size',3),
    ('boxer','Easy To Train',4),
    ('boxer','Energy Level',5),
    ('boxer','Exercise Needs',5),
    ('boykin spaniel','Adapts Well to Apartment Living',1),
    ('boykin spaniel','Good For Novice Owners',3),
    ('boykin spaniel','Sensitivity Level',4),
    ('boykin spaniel','Tolerates Being Alone',3),
    ('boykin spaniel','Affectionate with Family',5),
    ('boykin spaniel','Incredibly Kid Friendly Dogs',5),
    ('boykin spaniel','Dog Friendly',4),
    ('boykin spaniel','Amount Of Shedding',4),
    ('boykin spaniel','Size',3),
    ('boykin spaniel','Easy To Train',4),
    ('boykin spaniel','Energy Level',5),
    ('boykin spaniel','Exercise Needs',5),
    ('brittany','Adapts Well to Apartment Living',1),
    ('brittany','Good For Novice Owners',3),
    ('brittany','Sensitivity Level',5),
    ('brittany','Tolerates Being Alone',1),
    ('brittany','Affectionate with Family',5),
    ('brittany','Incredibly Kid Friendly Dogs',5),
    ('brittany','Dog Friendly',5),
    ('brittany','Amount Of Shedding',3),
    ('brittany','Size',3),
    ('brittany','Easy To Train',3),
    ('brittany','Energy Level',5),
    ('brittany','Exercise Needs',5),
    ('brussels griffon','Adapts Well to Apartment Living',5),
    ('brussels griffon','Good For Novice Owners',2),
    ('brussels griffon','Sensitivity Level',5),
    ('brussels griffon','Tolerates Being Alone',1),
    ('brussels griffon','Affectionate with Family',5),
    ('brussels griffon','Incredibly Kid Friendly Dogs',4),
    ('brussels griffon','Dog Friendly',4),
    ('brussels griffon','Amount Of Shedding',3),
    ('brussels griffon','Size',1),
    ('brussels griffon','Easy To Train',3),
    ('brussels griffon','Energy Level',5),
    ('brussels griffon','Exercise Needs',4),
    ('bull terrier','Adapts Well to Apartment Living',4),
    ('bull terrier','Good For Novice Owners',4),
    ('bull terrier','Sensitivity Level',5),
    ('bull terrier','Tolerates Being Alone',2),
    ('bull terrier','Affectionate with Family',5),
    ('bull terrier','Incredibly Kid Friendly Dogs',5),
    ('bull terrier','Dog Friendly',4),
    ('bull terrier','Amount Of Shedding',3),
    ('bull terrier','Size',2),
    ('bull terrier','Easy To Train',5),
    ('bull terrier','Energy Level',4),
    ('bull terrier','Exercise Needs',5),
    ('bulldog','Adapts Well to Apartment Living',5),
    ('bulldog','Good For Novice Owners',4),
    ('bulldog','Sensitivity Level',4),
    ('bulldog','Tolerates Being Alone',3),
    ('bulldog','Affectionate with Family',5),
    ('bulldog','Incredibly Kid Friendly Dogs',4),
    ('bulldog','Dog Friendly',2),
    ('bulldog','Amount Of Shedding',3),
    ('bulldog','Size',2),
    ('bulldog','Easy To Train',3),
    ('bulldog','Energy Level',2),
    ('bulldog','Exercise Needs',3),
    ('bullmastiff','Adapts Well to Apartment Living',3),
    ('bullmastiff','Good For Novice Owners',2),
    ('bullmastiff','Sensitivity Level',4),
    ('bullmastiff','Tolerates Being Alone',2),
    ('bullmastiff','Affectionate with Family',5),
    ('bullmastiff','Incredibly Kid Friendly Dogs',5),
    ('bullmastiff','Dog Friendly',4),
    ('bullmastiff','Amount Of Shedding',1),
    ('bullmastiff','Size',5),
    ('bullmastiff','Easy To Train',3),
    ('bullmastiff','Energy Level',2),
    ('bullmastiff','Exercise Needs',3),
    ('cairn terrier','Adapts Well to Apartment Living',5),
    ('cairn terrier','Good For Novice Owners',4),
    ('cairn terrier','Sensitivity Level',3),
    ('cairn terrier','Tolerates Being Alone',1),
    ('cairn terrier','Affectionate with Family',5),
    ('cairn terrier','Incredibly Kid Friendly Dogs',5),
    ('cairn terrier','Dog Friendly',4),
    ('cairn terrier','Amount Of Shedding',3),
    ('cairn terrier','Size',1),
    ('cairn terrier','Easy To Train',2),
    ('cairn terrier','Energy Level',5),
    ('cairn terrier','Exercise Needs',4),
    ('cane corso','Adapts Well to Apartment Living',1),
    ('cane corso','Good For Novice Owners',1),
    ('cane corso','Sensitivity Level',3),
    ('cane corso','Tolerates Being Alone',1),
    ('cane corso','Affectionate with Family',4),
    ('cane corso','Incredibly Kid Friendly Dogs',2),
    ('cane corso','Dog Friendly',3),
    ('cane corso','Amount Of Shedding',3),
    ('cane corso','Size',4),
    ('cane corso','Easy To Train',4),
    ('cane corso','Energy Level',4),
    ('cane corso','Exercise Needs',5),
    ('cardigan welsh corgi','Adapts Well to Apartment Living',4),
    ('cardigan welsh corgi','Good For Novice Owners',4),
    ('cardigan welsh corgi','Sensitivity Level',4),
    ('cardigan welsh corgi','Tolerates Being Alone',3),
    ('cardigan welsh corgi','Affectionate with Family',5),
    ('cardigan welsh corgi','Incredibly Kid Friendly Dogs',4),
    ('cardigan welsh corgi','Dog Friendly',3),
    ('cardigan welsh corgi','Amount Of Shedding',4),
    ('cardigan welsh corgi','Size',2),
    ('cardigan welsh corgi','Easy To Train',4),
    ('cardigan welsh corgi','Energy Level',3),
    ('cardigan welsh corgi','Exercise Needs',3),
    ('catahoula leopard dog','Adapts Well to Apartment Living',1),
    ('catahoula leopard dog','Good For Novice Owners',1),
    ('catahoula leopard dog','Sensitivity Level',2),
    ('catahoula leopard dog','Tolerates Being Alone',2),
    ('catahoula leopard dog','Affectionate with Family',5),
    ('catahoula leopard dog','Incredibly Kid Friendly Dogs',3),
    ('catahoula leopard dog','Dog Friendly',1),
    ('catahoula leopard dog','Amount Of Shedding',3),
    ('catahoula leopard dog','Size',4),
    ('catahoula leopard dog','Easy To Train',2),
    ('catahoula leopard dog','Energy Level',4),
    ('catahoula leopard dog','Exercise Needs',5),
    ('caucasian shepherd dog','Adapts Well to Apartment Living',2),
    ('caucasian shepherd dog','Good For Novice Owners',1),
    ('caucasian shepherd dog','Sensitivity Level',2),
    ('caucasian shepherd dog','Tolerates Being Alone',3),
    ('caucasian shepherd dog','Affectionate with Family',4),
    ('caucasian shepherd dog','Incredibly Kid Friendly Dogs',2),
    ('caucasian shepherd dog','Dog Friendly',2),
    ('caucasian shepherd dog','Amount Of Shedding',4),
    ('caucasian shepherd dog','Size',5),
    ('caucasian shepherd dog','Easy To Train',2),
    ('caucasian shepherd dog','Energy Level',2),
    ('caucasian shepherd dog','Exercise Needs',2),
    ('cavalier king charles spaniel','Adapts Well to Apartment Living',5),
    ('cavalier king charles spaniel','Good For Novice Owners',5),
    ('cavalier king charles spaniel','Sensitivity Level',5),
    ('cavalier king charles spaniel','Tolerates Being Alone',1),
    ('cavalier king charles spaniel','Affectionate with Family',5),
    ('cavalier king charles spaniel','Incredibly Kid Friendly Dogs',5),
    ('cavalier king charles spaniel','Dog Friendly',5),
    ('cavalier king charles spaniel','Amount Of Shedding',3),
    ('cavalier king charles spaniel','Size',2),
    ('cavalier king charles spaniel','Easy To Train',4),
    ('cavalier king charles spaniel','Energy Level',3),
    ('cavalier king charles spaniel','Exercise Needs',4),
    ('chesapeake bay retriever','Adapts Well to Apartment Living',1),
    ('chesapeake bay retriever','Good For Novice Owners',1),
    ('chesapeake bay retriever','Sensitivity Level',3),
    ('chesapeake bay retriever','Tolerates Being Alone',2),
    ('chesapeake bay retriever','Affectionate with Family',5),
    ('chesapeake bay retriever','Incredibly Kid Friendly Dogs',3),
    ('chesapeake bay retriever','Dog Friendly',1),
    ('chesapeake bay retriever','Amount Of Shedding',5);
INSERT INTO breeds VALUES
    ('chesapeake bay retriever','Size',3),
    ('chesapeake bay retriever','Easy To Train',3),
    ('chesapeake bay retriever','Energy Level',5),
    ('chesapeake bay retriever','Exercise Needs',5),
    ('chihuahua','Adapts Well to Apartment Living',5),
    ('chihuahua','Good For Novice Owners',4),
    ('chihuahua','Sensitivity Level',5),
    ('chihuahua','Tolerates Being Alone',1),
    ('chihuahua','Affectionate with Family',5),
    ('chihuahua','Incredibly Kid Friendly Dogs',5),
    ('chihuahua','Dog Friendly',2),
    ('chihuahua','Amount Of Shedding',2),
    ('chihuahua','Size',1),
    ('chihuahua','Easy To Train',4),
    ('chihuahua','Energy Level',3),
    ('chihuahua','Exercise Needs',1),
    ('chinese crested','Adapts Well to Apartment Living',5),
    ('chinese crested','Good For Novice Owners',3),
    ('chinese crested','Sensitivity Level',5),
    ('chinese crested','Tolerates Being Alone',1),
    ('chinese crested','Affectionate with Family',4),
    ('chinese crested','Incredibly Kid Friendly Dogs',5),
    ('chinese crested','Dog Friendly',4),
    ('chinese crested','Amount Of Shedding',2),
    ('chinese crested','Size',2),
    ('chinese crested','Easy To Train',4),
    ('chinese crested','Energy Level',2),
    ('chinese crested','Exercise Needs',2),
    ('chinese shar pei','Adapts Well to Apartment Living',4),
    ('chinese shar pei','Good For Novice Owners',2),
    ('chinese shar pei','Sensitivity Level',2),
    ('chinese shar pei','Tolerates Being Alone',4),
    ('chinese shar pei','Affectionate with Family',2),
    ('chinese shar pei','Incredibly Kid Friendly Dogs',2),
    ('chinese shar pei','Dog Friendly',1),
    ('chinese shar pei','Amount Of Shedding',5),
    ('chinese shar pei','Size',3),
    ('chinese shar pei','Easy To Train',3),
    ('chinese shar pei','Energy Level',2),
    ('chinese shar pei','Exercise Needs',3),
    ('chinook','Adapts Well to Apartment Living',4),
    ('chinook','Good For Novice Owners',1),
    ('chinook','Sensitivity Level',5),
    ('chinook','Tolerates Being Alone',1),
    ('chinook','Affectionate with Family',5),
    ('chinook','Incredibly Kid Friendly Dogs',5),
    ('chinook','Dog Friendly',5),
    ('chinook','Amount Of Shedding',5),
    ('chinook','Size',4),
    ('chinook','Easy To Train',4),
    ('chinook','Energy Level',3),
    ('chinook','Exercise Needs',3),
    ('chow chow','Adapts Well to Apartment Living',3),
    ('chow chow','Good For Novice Owners',2),
    ('chow chow','Sensitivity Level',2),
    ('chow chow','Tolerates Being Alone',5),
    ('chow chow','Affectionate with Family',2),
    ('chow chow','Incredibly Kid Friendly Dogs',1),
    ('chow chow','Dog Friendly',1),
    ('chow chow','Amount Of Shedding',1),
    ('chow chow','Size',4),
    ('chow chow','Easy To Train',2),
    ('chow chow','Energy Level',2),
    ('chow chow','Exercise Needs',2),
    ('clumber spaniel','Adapts Well to Apartment Living',5),
    ('clumber spaniel','Good For Novice Owners',5),
    ('clumber spaniel','Sensitivity Level',4),
    ('clumber spaniel','Tolerates Being Alone',2),
    ('clumber spaniel','Affectionate with Family',5),
    ('clumber spaniel','Incredibly Kid Friendly Dogs',3),
    ('clumber spaniel','Dog Friendly',4),
    ('clumber spaniel','Amount Of Shedding',5),
    ('clumber spaniel','Size',3),
    ('clumber spaniel','Easy To Train',4),
    ('clumber spaniel','Energy Level',3),
    ('clumber spaniel','Exercise Needs',2),
    ('cockapoo','Adapts Well to Apartment Living',4),
    ('cockapoo','Good For Novice Owners',5),
    ('cockapoo','Sensitivity Level',4),
    ('cockapoo','Tolerates Being Alone',3),
    ('cockapoo','Affectionate with Family',5),
    ('cockapoo','Incredibly Kid Friendly Dogs',4),
    ('cockapoo','Dog Friendly',5),
    ('cockapoo','Amount Of Shedding',1),
    ('cockapoo','Size',2),
    ('cockapoo','Easy To Train',4),
    ('cockapoo','Energy Level',3),
    ('cockapoo','Exercise Needs',3),
    ('cocker spaniel','Adapts Well to Apartment Living',5),
    ('cocker spaniel','Good For Novice Owners',3),
    ('cocker spaniel','Sensitivity Level',5),
    ('cocker spaniel','Tolerates Being Alone',1),
    ('cocker spaniel','Affectionate with Family',5),
    ('cocker spaniel','Incredibly Kid Friendly Dogs',3),
    ('cocker spaniel','Dog Friendly',4),
    ('cocker spaniel','Amount Of Shedding',3),
    ('cocker spaniel','Size',2),
    ('cocker spaniel','Easy To Train',5),
    ('cocker spaniel','Energy Level',4),
    ('cocker spaniel','Exercise Needs',3),
    ('collie','Adapts Well to Apartment Living',3),
    ('collie','Good For Novice Owners',4),
    ('collie','Sensitivity Level',5),
    ('collie','Tolerates Being Alone',2),
    ('collie','Affectionate with Family',5),
    ('collie','Incredibly Kid Friendly Dogs',5),
    ('collie','Dog Friendly',4),
    ('collie','Amount Of Shedding',5),
    ('collie','Size',3),
    ('collie','Easy To Train',4),
    ('collie','Energy Level',3),
    ('collie','Exercise Needs',3),
    ('curly coated retriever','Adapts Well to Apartment Living',1),
    ('curly coated retriever','Good For Novice Owners',3),
    ('curly coated retriever','Sensitivity Level',3),
    ('curly coated retriever','Tolerates Being Alone',3),
    ('curly coated retriever','Affectionate with Family',5),
    ('curly coated retriever','Incredibly Kid Friendly Dogs',5),
    ('curly coated retriever','Dog Friendly',4),
    ('curly coated retriever','Amount Of Shedding',3),
    ('curly coated retriever','Size',3),
    ('curly coated retriever','Easy To Train',4),
    ('curly coated retriever','Energy Level',5),
    ('curly coated retriever','Exercise Needs',4),
    ('dachshund','Adapts Well to Apartment Living',5),
    ('dachshund','Good For Novice Owners',4),
    ('dachshund','Sensitivity Level',4),
    ('dachshund','Tolerates Being Alone',3),
    ('dachshund','Affectionate with Family',4),
    ('dachshund','Incredibly Kid Friendly Dogs',5),
    ('dachshund','Dog Friendly',3),
    ('dachshund','Amount Of Shedding',3),
    ('dachshund','Size',1),
    ('dachshund','Easy To Train',2),
    ('dachshund','Energy Level',3),
    ('dachshund','Exercise Needs',3),
    ('dalmatian','Adapts Well to Apartment Living',2),
    ('dalmatian','Good For Novice Owners',3),
    ('dalmatian','Sensitivity Level',4),
    ('dalmatian','Tolerates Being Alone',3),
    ('dalmatian','Affectionate with Family',5),
    ('dalmatian','Incredibly Kid Friendly Dogs',4),
    ('dalmatian','Dog Friendly',4),
    ('dalmatian','Amount Of Shedding',5),
    ('dalmatian','Size',3),
    ('dalmatian','Easy To Train',4),
    ('dalmatian','Energy Level',5),
    ('dalmatian','Exercise Needs',5),
    ('doberman pinscher','Adapts Well to Apartment Living',3),
    ('doberman pinscher','Good For Novice Owners',3),
    ('doberman pinscher','Sensitivity Level',5),
    ('doberman pinscher','Tolerates Being Alone',2),
    ('doberman pinscher','Affectionate with Family',5),
    ('doberman pinscher','Incredibly Kid Friendly Dogs',3),
    ('doberman pinscher','Dog Friendly',1),
    ('doberman pinscher','Amount Of Shedding',4),
    ('doberman pinscher','Size',4),
    ('doberman pinscher','Easy To Train',5),
    ('doberman pinscher','Energy Level',3),
    ('doberman pinscher','Exercise Needs',3),
    ('dogo argentino','Adapts Well to Apartment Living',1),
    ('dogo argentino','Good For Novice Owners',1),
    ('dogo argentino','Sensitivity Level',3),
    ('dogo argentino','Tolerates Being Alone',2),
    ('dogo argentino','Affectionate with Family',4),
    ('dogo argentino','Incredibly Kid Friendly Dogs',2),
    ('dogo argentino','Dog Friendly',2),
    ('dogo argentino','Amount Of Shedding',1),
    ('dogo argentino','Size',4),
    ('dogo argentino','Easy To Train',2),
    ('dogo argentino','Energy Level',4),
    ('dogo argentino','Exercise Needs',4),
    ('dogue de bordeaux','Adapts Well to Apartment Living',5),
    ('dogue de bordeaux','Good For Novice Owners',1),
    ('dogue de bordeaux','Sensitivity Level',4),
    ('dogue de bordeaux','Tolerates Being Alone',2),
    ('dogue de bordeaux','Affectionate with Family',5),
    ('dogue de bordeaux','Incredibly Kid Friendly Dogs',5),
    ('dogue de bordeaux','Dog Friendly',1),
    ('dogue de bordeaux','Amount Of Shedding',3),
    ('dogue de bordeaux','Size',4),
    ('dogue de bordeaux','Easy To Train',2),
    ('dogue de bordeaux','Energy Level',2),
    ('dogue de bordeaux','Exercise Needs',5),
    ('dutch shepherd','Adapts Well to Apartment Living',3),
    ('dutch shepherd','Good For Novice Owners',3),
    ('dutch shepherd','Sensitivity Level',3),
    ('dutch shepherd','Tolerates Being Alone',2),
    ('dutch shepherd','Affectionate with Family',4),
    ('dutch shepherd','Incredibly Kid Friendly Dogs',4),
    ('dutch shepherd','Dog Friendly',4),
    ('dutch shepherd','Amount Of Shedding',4),
    ('dutch shepherd','Size',3),
    ('dutch shepherd','Easy To Train',5),
    ('dutch shepherd','Energy Level',4),
    ('dutch shepherd','Exercise Needs',4),
    ('english cocker spaniel','Adapts Well to Apartment Living',5),
    ('english cocker spaniel','Good For Novice Owners',4),
    ('english cocker spaniel','Sensitivity Level',5),
    ('english cocker spaniel','Tolerates Being Alone',1),
    ('english cocker spaniel','Affectionate with Family',5),
    ('english cocker spaniel','Incredibly Kid Friendly Dogs',5),
    ('english cocker spaniel','Dog Friendly',5),
    ('english cocker spaniel','Amount Of Shedding',3),
    ('english cocker spaniel','Size',2),
    ('english cocker spaniel','Easy To Train',4),
    ('english cocker spaniel','Energy Level',5),
    ('english cocker spaniel','Exercise Needs',4),
    ('english foxhound','Adapts Well to Apartment Living',1),
    ('english foxhound','Good For Novice Owners',2),
    ('english foxhound','Sensitivity Level',3),
    ('english foxhound','Tolerates Being Alone',4),
    ('english foxhound','Affectionate with Family',4),
    ('english foxhound','Incredibly Kid Friendly Dogs',4),
    ('english foxhound','Dog Friendly',5),
    ('english foxhound','Amount Of Shedding',3),
    ('english foxhound','Size',3),
    ('english foxhound','Easy To Train',3),
    ('english foxhound','Energy Level',5),
    ('english foxhound','Exercise Needs',5),
    ('english setter','Adapts Well to Apartment Living',1),
    ('english setter','Good For Novice Owners',3),
    ('english setter','Sensitivity Level',4),
    ('english setter','Tolerates Being Alone',1),
    ('english setter','Affectionate with Family',5),
    ('english setter','Incredibly Kid Friendly Dogs',5),
    ('english setter','Dog Friendly',5),
    ('english setter','Amount Of Shedding',3),
    ('english setter','Size',3),
    ('english setter','Easy To Train',3),
    ('english setter','Energy Level',4),
    ('english setter','Exercise Needs',5),
    ('english springer spaniel','Adapts Well to Apartment Living',1),
    ('english springer spaniel','Good For Novice Owners',3),
    ('english springer spaniel','Sensitivity Level',4),
    ('english springer spaniel','Tolerates Being Alone',1),
    ('english springer spaniel','Affectionate with Family',5),
    ('english springer spaniel','Incredibly Kid Friendly Dogs',5),
    ('english springer spaniel','Dog Friendly',5),
    ('english springer spaniel','Amount Of Shedding',3),
    ('english springer spaniel','Size',3),
    ('english springer spaniel','Easy To Train',5),
    ('english springer spaniel','Energy Level',5),
    ('english springer spaniel','Exercise Needs',5),
    ('english toy spaniel','Adapts Well to Apartment Living',4),
    ('english toy spaniel','Good For Novice Owners',4),
    ('english toy spaniel','Sensitivity Level',4),
    ('english toy spaniel','Tolerates Being Alone',1),
    ('english toy spaniel','Affectionate with Family',5),
    ('english toy spaniel','Incredibly Kid Friendly Dogs',1);
INSERT INTO breeds VALUES
    ('english toy spaniel','Dog Friendly',4),
    ('english toy spaniel','Amount Of Shedding',5),
    ('english toy spaniel','Size',2),
    ('english toy spaniel','Easy To Train',3),
    ('english toy spaniel','Energy Level',3),
    ('english toy spaniel','Exercise Needs',2),
    ('finnish lapphund','Adapts Well to Apartment Living',4),
    ('finnish lapphund','Good For Novice Owners',4),
    ('finnish lapphund','Sensitivity Level',4),
    ('finnish lapphund','Tolerates Being Alone',2),
    ('finnish lapphund','Affectionate with Family',5),
    ('finnish lapphund','Incredibly Kid Friendly Dogs',5),
    ('finnish lapphund','Dog Friendly',5),
    ('finnish lapphund','Amount Of Shedding',3),
    ('finnish lapphund','Size',3),
    ('finnish lapphund','Easy To Train',5),
    ('finnish lapphund','Energy Level',5),
    ('finnish lapphund','Exercise Needs',4),
    ('finnish spitz','Adapts Well to Apartment Living',3),
    ('finnish spitz','Good For Novice Owners',3),
    ('finnish spitz','Sensitivity Level',3),
    ('finnish spitz','Tolerates Being Alone',1),
    ('finnish spitz','Affectionate with Family',5),
    ('finnish spitz','Incredibly Kid Friendly Dogs',5),
    ('finnish spitz','Dog Friendly',5),
    ('finnish spitz','Amount Of Shedding',4),
    ('finnish spitz','Size',3),
    ('finnish spitz','Easy To Train',3),
    ('finnish spitz','Energy Level',5),
    ('finnish spitz','Exercise Needs',5),
    ('flat coated retriever','Adapts Well to Apartment Living',1),
    ('flat coated retriever','Good For Novice Owners',2),
    ('flat coated retriever','Sensitivity Level',5),
    ('flat coated retriever','Tolerates Being Alone',1),
    ('flat coated retriever','Affectionate with Family',5),
    ('flat coated retriever','Incredibly Kid Friendly Dogs',5),
    ('flat coated retriever','Dog Friendly',5),
    ('flat coated retriever','Amount Of Shedding',3),
    ('flat coated retriever','Size',3),
    ('flat coated retriever','Easy To Train',4),
    ('flat coated retriever','Energy Level',5),
    ('flat coated retriever','Exercise Needs',5),
    ('fox terrier','Adapts Well to Apartment Living',3),
    ('fox terrier','Good For Novice Owners',3),
    ('fox terrier','Sensitivity Level',3),
    ('fox terrier','Tolerates Being Alone',3),
    ('fox terrier','Affectionate with Family',4),
    ('fox terrier','Incredibly Kid Friendly Dogs',4),
    ('fox terrier','Dog Friendly',3),
    ('fox terrier','Amount Of Shedding',2),
    ('fox terrier','Size',2),
    ('fox terrier','Easy To Train',5),
    ('fox terrier','Energy Level',5),
    ('fox terrier','Exercise Needs',5),
    ('french bulldog','Adapts Well to Apartment Living',5),
    ('french bulldog','Good For Novice Owners',5),
    ('french bulldog','Sensitivity Level',3),
    ('french bulldog','Tolerates Being Alone',1),
    ('french bulldog','Affectionate with Family',5),
    ('french bulldog','Incredibly Kid Friendly Dogs',4),
    ('french bulldog','Dog Friendly',4),
    ('french bulldog','Amount Of Shedding',3),
    ('french bulldog','Size',2),
    ('french bulldog','Easy To Train',4),
    ('french bulldog','Energy Level',3),
    ('french bulldog','Exercise Needs',2),
    ('german pinscher','Adapts Well to Apartment Living',3),
    ('german pinscher','Good For Novice Owners',3),
    ('german pinscher','Sensitivity Level',4),
    ('german pinscher','Tolerates Being Alone',3),
    ('german pinscher','Affectionate with Family',5),
    ('german pinscher','Incredibly Kid Friendly Dogs',3),
    ('german pinscher','Dog Friendly',2),
    ('german pinscher','Amount Of Shedding',3),
    ('german pinscher','Size',3),
    ('german pinscher','Easy To Train',4),
    ('german pinscher','Energy Level',5),
    ('german pinscher','Exercise Needs',5),
    ('german shepherd dog','Adapts Well to Apartment Living',3),
    ('german shepherd dog','Good For Novice Owners',2),
    ('german shepherd dog','Sensitivity Level',5),
    ('german shepherd dog','Tolerates Being Alone',2),
    ('german shepherd dog','Affectionate with Family',5),
    ('german shepherd dog','Incredibly Kid Friendly Dogs',5),
    ('german shepherd dog','Dog Friendly',2),
    ('german shepherd dog','Amount Of Shedding',5),
    ('german shepherd dog','Size',4),
    ('german shepherd dog','Easy To Train',5),
    ('german shepherd dog','Energy Level',5),
    ('german shepherd dog','Exercise Needs',5),
    ('german shorthaired pointer','Adapts Well to Apartment Living',1),
    ('german shorthaired pointer','Good For Novice Owners',2),
    ('german shorthaired pointer','Sensitivity Level',4),
    ('german shorthaired pointer','Tolerates Being Alone',1),
    ('german shorthaired pointer','Affectionate with Family',5),
    ('german shorthaired pointer','Incredibly Kid Friendly Dogs',5),
    ('german shorthaired pointer','Dog Friendly',4),
    ('german shorthaired pointer','Amount Of Shedding',2),
    ('german shorthaired pointer','Size',3),
    ('german shorthaired pointer','Easy To Train',5),
    ('german shorthaired pointer','Energy Level',5),
    ('german shorthaired pointer','Exercise Needs',5),
    ('german wirehaired pointer','Adapts Well to Apartment Living',2),
    ('german wirehaired pointer','Good For Novice Owners',3),
    ('german wirehaired pointer','Sensitivity Level',4),
    ('german wirehaired pointer','Tolerates Being Alone',2),
    ('german wirehaired pointer','Affectionate with Family',5),
    ('german wirehaired pointer','Incredibly Kid Friendly Dogs',3),
    ('german wirehaired pointer','Dog Friendly',3),
    ('german wirehaired pointer','Amount Of Shedding',2),
    ('german wirehaired pointer','Size',4),
    ('german wirehaired pointer','Easy To Train',4),
    ('german wirehaired pointer','Energy Level',5),
    ('german wirehaired pointer','Exercise Needs',5),
    ('giant schnauzer','Adapts Well to Apartment Living',1),
    ('giant schnauzer','Good For Novice Owners',1),
    ('giant schnauzer','Sensitivity Level',4),
    ('giant schnauzer','Tolerates Being Alone',2),
    ('giant schnauzer','Affectionate with Family',5),
    ('giant schnauzer','Incredibly Kid Friendly Dogs',3),
    ('giant schnauzer','Dog Friendly',3),
    ('giant schnauzer','Amount Of Shedding',4),
    ('giant schnauzer','Size',4),
    ('giant schnauzer','Easy To Train',5),
    ('giant schnauzer','Energy Level',5),
    ('giant schnauzer','Exercise Needs',5),
    ('golden retriever','Adapts Well to Apartment Living',2),
    ('golden retriever','Good For Novice Owners',3),
    ('golden retriever','Sensitivity Level',5),
    ('golden retriever','Tolerates Being Alone',1),
    ('golden retriever','Affectionate with Family',5),
    ('golden retriever','Incredibly Kid Friendly Dogs',5),
    ('golden retriever','Dog Friendly',5),
    ('golden retriever','Amount Of Shedding',5),
    ('golden retriever','Size',3),
    ('golden retriever','Easy To Train',5),
    ('golden retriever','Energy Level',5),
    ('golden retriever','Exercise Needs',5),
    ('goldendoodle','Adapts Well to Apartment Living',1),
    ('goldendoodle','Good For Novice Owners',4),
    ('goldendoodle','Sensitivity Level',4),
    ('goldendoodle','Tolerates Being Alone',3),
    ('goldendoodle','Affectionate with Family',5),
    ('goldendoodle','Incredibly Kid Friendly Dogs',5),
    ('goldendoodle','Dog Friendly',5),
    ('goldendoodle','Amount Of Shedding',2),
    ('goldendoodle','Size',4),
    ('goldendoodle','Easy To Train',4),
    ('goldendoodle','Energy Level',4),
    ('goldendoodle','Exercise Needs',5),
    ('great dane','Adapts Well to Apartment Living',1),
    ('great dane','Good For Novice Owners',1),
    ('great dane','Sensitivity Level',5),
    ('great dane','Tolerates Being Alone',1),
    ('great dane','Affectionate with Family',5),
    ('great dane','Incredibly Kid Friendly Dogs',5),
    ('great dane','Dog Friendly',5),
    ('great dane','Amount Of Shedding',5),
    ('great dane','Size',5),
    ('great dane','Easy To Train',5),
    ('great dane','Energy Level',5),
    ('great dane','Exercise Needs',5),
    ('great pyrenees','Adapts Well to Apartment Living',1),
    ('great pyrenees','Good For Novice Owners',1),
    ('great pyrenees','Sensitivity Level',4),
    ('great pyrenees','Tolerates Being Alone',3),
    ('great pyrenees','Affectionate with Family',5),
    ('great pyrenees','Incredibly Kid Friendly Dogs',4),
    ('great pyrenees','Dog Friendly',4),
    ('great pyrenees','Amount Of Shedding',5),
    ('great pyrenees','Size',5),
    ('great pyrenees','Easy To Train',1),
    ('great pyrenees','Energy Level',5),
    ('great pyrenees','Exercise Needs',5),
    ('greater swiss mountain dog','Adapts Well to Apartment Living',1),
    ('greater swiss mountain dog','Good For Novice Owners',2),
    ('greater swiss mountain dog','Sensitivity Level',4),
    ('greater swiss mountain dog','Tolerates Being Alone',3),
    ('greater swiss mountain dog','Affectionate with Family',5),
    ('greater swiss mountain dog','Incredibly Kid Friendly Dogs',5),
    ('greater swiss mountain dog','Dog Friendly',5),
    ('greater swiss mountain dog','Amount Of Shedding',3),
    ('greater swiss mountain dog','Size',5),
    ('greater swiss mountain dog','Easy To Train',3),
    ('greater swiss mountain dog','Energy Level',5),
    ('greater swiss mountain dog','Exercise Needs',3),
    ('greyhound','Adapts Well to Apartment Living',4),
    ('greyhound','Good For Novice Owners',2),
    ('greyhound','Sensitivity Level',5),
    ('greyhound','Tolerates Being Alone',1),
    ('greyhound','Affectionate with Family',5),
    ('greyhound','Incredibly Kid Friendly Dogs',5),
    ('greyhound','Dog Friendly',4),
    ('greyhound','Amount Of Shedding',4),
    ('greyhound','Size',4),
    ('greyhound','Easy To Train',5),
    ('greyhound','Energy Level',5),
    ('greyhound','Exercise Needs',5),
    ('harrier','Adapts Well to Apartment Living',1),
    ('harrier','Good For Novice Owners',3),
    ('harrier','Sensitivity Level',2),
    ('harrier','Tolerates Being Alone',3),
    ('harrier','Affectionate with Family',4),
    ('harrier','Incredibly Kid Friendly Dogs',5),
    ('harrier','Dog Friendly',5),
    ('harrier','Amount Of Shedding',3),
    ('harrier','Size',3),
    ('harrier','Easy To Train',2),
    ('harrier','Energy Level',5),
    ('harrier','Exercise Needs',5),
    ('havanese','Adapts Well to Apartment Living',5),
    ('havanese','Good For Novice Owners',5),
    ('havanese','Sensitivity Level',4),
    ('havanese','Tolerates Being Alone',1),
    ('havanese','Affectionate with Family',5),
    ('havanese','Incredibly Kid Friendly Dogs',4),
    ('havanese','Dog Friendly',5),
    ('havanese','Amount Of Shedding',2),
    ('havanese','Size',2),
    ('havanese','Easy To Train',5),
    ('havanese','Energy Level',3),
    ('havanese','Exercise Needs',3),
    ('ibizan hound','Adapts Well to Apartment Living',5),
    ('ibizan hound','Good For Novice Owners',3),
    ('ibizan hound','Sensitivity Level',4),
    ('ibizan hound','Tolerates Being Alone',2),
    ('ibizan hound','Affectionate with Family',5),
    ('ibizan hound','Incredibly Kid Friendly Dogs',5),
    ('ibizan hound','Dog Friendly',5),
    ('ibizan hound','Amount Of Shedding',3),
    ('ibizan hound','Size',3),
    ('ibizan hound','Easy To Train',3),
    ('ibizan hound','Energy Level',5),
    ('ibizan hound','Exercise Needs',5),
    ('icelandic sheepdog','Adapts Well to Apartment Living',1),
    ('icelandic sheepdog','Good For Novice Owners',1),
    ('icelandic sheepdog','Sensitivity Level',3),
    ('icelandic sheepdog','Tolerates Being Alone',2),
    ('icelandic sheepdog','Affectionate with Family',4),
    ('icelandic sheepdog','Incredibly Kid Friendly Dogs',4),
    ('icelandic sheepdog','Dog Friendly',2),
    ('icelandic sheepdog','Amount Of Shedding',5),
    ('icelandic sheepdog','Size',3),
    ('icelandic sheepdog','Easy To Train',3),
    ('icelandic sheepdog','Energy Level',4),
    ('icelandic sheepdog','Exercise Needs',4),
    ('irish setter','Adapts Well to Apartment Living',1),
    ('irish setter','Good For Novice Owners',3),
    ('irish setter','Sensitivity Level',4),
    ('irish setter','Tolerates Being Alone',2);
INSERT INTO breeds VALUES
    ('irish setter','Affectionate with Family',5),
    ('irish setter','Incredibly Kid Friendly Dogs',5),
    ('irish setter','Dog Friendly',5),
    ('irish setter','Amount Of Shedding',4),
    ('irish setter','Size',4),
    ('irish setter','Easy To Train',4),
    ('irish setter','Energy Level',5),
    ('irish setter','Exercise Needs',5),
    ('irish terrier','Adapts Well to Apartment Living',3),
    ('irish terrier','Good For Novice Owners',2),
    ('irish terrier','Sensitivity Level',3),
    ('irish terrier','Tolerates Being Alone',2),
    ('irish terrier','Affectionate with Family',5),
    ('irish terrier','Incredibly Kid Friendly Dogs',5),
    ('irish terrier','Dog Friendly',1),
    ('irish terrier','Amount Of Shedding',4),
    ('irish terrier','Size',3),
    ('irish terrier','Easy To Train',1),
    ('irish terrier','Energy Level',5),
    ('irish terrier','Exercise Needs',4),
    ('irish wolfhound','Adapts Well to Apartment Living',1),
    ('irish wolfhound','Good For Novice Owners',2),
    ('irish wolfhound','Sensitivity Level',3),
    ('irish wolfhound','Tolerates Being Alone',2),
    ('irish wolfhound','Affectionate with Family',5),
    ('irish wolfhound','Incredibly Kid Friendly Dogs',5),
    ('irish wolfhound','Dog Friendly',5),
    ('irish wolfhound','Amount Of Shedding',3),
    ('irish wolfhound','Size',5),
    ('irish wolfhound','Easy To Train',3),
    ('irish wolfhound','Energy Level',2),
    ('irish wolfhound','Exercise Needs',4),
    ('italian greyhound','Adapts Well to Apartment Living',5),
    ('italian greyhound','Good For Novice Owners',5),
    ('italian greyhound','Sensitivity Level',5),
    ('italian greyhound','Tolerates Being Alone',1),
    ('italian greyhound','Affectionate with Family',5),
    ('italian greyhound','Incredibly Kid Friendly Dogs',5),
    ('italian greyhound','Dog Friendly',4),
    ('italian greyhound','Amount Of Shedding',2),
    ('italian greyhound','Size',2),
    ('italian greyhound','Easy To Train',3),
    ('italian greyhound','Energy Level',4),
    ('italian greyhound','Exercise Needs',4),
    ('jack russell terrier','Adapts Well to Apartment Living',3),
    ('jack russell terrier','Good For Novice Owners',2),
    ('jack russell terrier','Sensitivity Level',3),
    ('jack russell terrier','Tolerates Being Alone',3),
    ('jack russell terrier','Affectionate with Family',5),
    ('jack russell terrier','Incredibly Kid Friendly Dogs',4),
    ('jack russell terrier','Dog Friendly',5),
    ('jack russell terrier','Amount Of Shedding',3),
    ('jack russell terrier','Size',2),
    ('jack russell terrier','Easy To Train',4),
    ('jack russell terrier','Energy Level',5),
    ('jack russell terrier','Exercise Needs',5),
    ('japanese chin','Adapts Well to Apartment Living',5),
    ('japanese chin','Good For Novice Owners',4),
    ('japanese chin','Sensitivity Level',3),
    ('japanese chin','Tolerates Being Alone',1),
    ('japanese chin','Affectionate with Family',3),
    ('japanese chin','Incredibly Kid Friendly Dogs',3),
    ('japanese chin','Dog Friendly',3),
    ('japanese chin','Amount Of Shedding',3),
    ('japanese chin','Size',1),
    ('japanese chin','Easy To Train',3),
    ('japanese chin','Energy Level',2),
    ('japanese chin','Exercise Needs',2),
    ('japanese spitz','Adapts Well to Apartment Living',4),
    ('japanese spitz','Good For Novice Owners',4),
    ('japanese spitz','Sensitivity Level',3),
    ('japanese spitz','Tolerates Being Alone',2),
    ('japanese spitz','Affectionate with Family',4),
    ('japanese spitz','Incredibly Kid Friendly Dogs',5),
    ('japanese spitz','Dog Friendly',4),
    ('japanese spitz','Amount Of Shedding',3),
    ('japanese spitz','Size',2),
    ('japanese spitz','Easy To Train',4),
    ('japanese spitz','Energy Level',3),
    ('japanese spitz','Exercise Needs',3),
    ('karelian bear dog','Adapts Well to Apartment Living',2),
    ('karelian bear dog','Good For Novice Owners',1),
    ('karelian bear dog','Sensitivity Level',4),
    ('karelian bear dog','Tolerates Being Alone',2),
    ('karelian bear dog','Affectionate with Family',4),
    ('karelian bear dog','Incredibly Kid Friendly Dogs',3),
    ('karelian bear dog','Dog Friendly',1),
    ('karelian bear dog','Amount Of Shedding',3),
    ('karelian bear dog','Size',3),
    ('karelian bear dog','Easy To Train',2),
    ('karelian bear dog','Energy Level',4),
    ('karelian bear dog','Exercise Needs',4),
    ('jindo','Adapts Well to Apartment Living',3),
    ('jindo','Good For Novice Owners',2),
    ('jindo','Sensitivity Level',3),
    ('jindo','Tolerates Being Alone',2),
    ('jindo','Affectionate with Family',5),
    ('jindo','Incredibly Kid Friendly Dogs',3),
    ('jindo','Dog Friendly',3),
    ('jindo','Amount Of Shedding',5),
    ('jindo','Size',3),
    ('jindo','Easy To Train',2),
    ('jindo','Energy Level',4),
    ('jindo','Exercise Needs',5),
    ('labradoodle','Adapts Well to Apartment Living',3),
    ('labradoodle','Good For Novice Owners',4),
    ('labradoodle','Sensitivity Level',3),
    ('labradoodle','Tolerates Being Alone',4),
    ('labradoodle','Affectionate with Family',5),
    ('labradoodle','Incredibly Kid Friendly Dogs',4),
    ('labradoodle','Dog Friendly',5),
    ('labradoodle','Amount Of Shedding',3),
    ('labradoodle','Size',4),
    ('labradoodle','Easy To Train',4),
    ('labradoodle','Energy Level',5),
    ('labradoodle','Exercise Needs',5),
    ('labrador retriever','Adapts Well to Apartment Living',1),
    ('labrador retriever','Good For Novice Owners',3),
    ('labrador retriever','Sensitivity Level',5),
    ('labrador retriever','Tolerates Being Alone',2),
    ('labrador retriever','Affectionate with Family',5),
    ('labrador retriever','Incredibly Kid Friendly Dogs',5),
    ('labrador retriever','Dog Friendly',5),
    ('labrador retriever','Amount Of Shedding',5),
    ('labrador retriever','Size',4),
    ('labrador retriever','Easy To Train',5),
    ('labrador retriever','Energy Level',5),
    ('labrador retriever','Exercise Needs',5),
    ('maltese','Adapts Well to Apartment Living',5),
    ('maltese','Good For Novice Owners',5),
    ('maltese','Sensitivity Level',4),
    ('maltese','Tolerates Being Alone',1),
    ('maltese','Affectionate with Family',5),
    ('maltese','Incredibly Kid Friendly Dogs',3),
    ('maltese','Dog Friendly',4),
    ('maltese','Amount Of Shedding',2),
    ('maltese','Size',1),
    ('maltese','Easy To Train',4),
    ('maltese','Energy Level',3),
    ('maltese','Exercise Needs',2),
    ('maltese shih tzu','Adapts Well to Apartment Living',5),
    ('maltese shih tzu','Good For Novice Owners',5),
    ('maltese shih tzu','Sensitivity Level',3),
    ('maltese shih tzu','Tolerates Being Alone',3),
    ('maltese shih tzu','Affectionate with Family',4),
    ('maltese shih tzu','Incredibly Kid Friendly Dogs',3),
    ('maltese shih tzu','Dog Friendly',3),
    ('maltese shih tzu','Amount Of Shedding',1),
    ('maltese shih tzu','Size',1),
    ('maltese shih tzu','Easy To Train',4),
    ('maltese shih tzu','Energy Level',3),
    ('maltese shih tzu','Exercise Needs',3),
    ('maltipoo','Adapts Well to Apartment Living',5),
    ('maltipoo','Good For Novice Owners',5),
    ('maltipoo','Sensitivity Level',5),
    ('maltipoo','Tolerates Being Alone',1),
    ('maltipoo','Affectionate with Family',5),
    ('maltipoo','Incredibly Kid Friendly Dogs',4),
    ('maltipoo','Dog Friendly',4),
    ('maltipoo','Amount Of Shedding',1),
    ('maltipoo','Size',2),
    ('maltipoo','Easy To Train',5),
    ('maltipoo','Energy Level',3),
    ('maltipoo','Exercise Needs',2),
    ('manchester terrier','Adapts Well to Apartment Living',5),
    ('manchester terrier','Good For Novice Owners',3),
    ('manchester terrier','Sensitivity Level',3),
    ('manchester terrier','Tolerates Being Alone',3),
    ('manchester terrier','Affectionate with Family',4),
    ('manchester terrier','Incredibly Kid Friendly Dogs',3),
    ('manchester terrier','Dog Friendly',3),
    ('manchester terrier','Amount Of Shedding',3),
    ('manchester terrier','Size',2),
    ('manchester terrier','Easy To Train',2),
    ('manchester terrier','Energy Level',4),
    ('manchester terrier','Exercise Needs',4),
    ('mastiff','Adapts Well to Apartment Living',2),
    ('mastiff','Good For Novice Owners',1),
    ('mastiff','Sensitivity Level',3),
    ('mastiff','Tolerates Being Alone',3),
    ('mastiff','Affectionate with Family',5),
    ('mastiff','Incredibly Kid Friendly Dogs',5),
    ('mastiff','Dog Friendly',2),
    ('mastiff','Amount Of Shedding',3),
    ('mastiff','Size',5),
    ('mastiff','Easy To Train',3),
    ('mastiff','Energy Level',3),
    ('mastiff','Exercise Needs',4),
    ('miniature pinscher','Adapts Well to Apartment Living',5),
    ('miniature pinscher','Good For Novice Owners',3),
    ('miniature pinscher','Sensitivity Level',5),
    ('miniature pinscher','Tolerates Being Alone',2),
    ('miniature pinscher','Affectionate with Family',5),
    ('miniature pinscher','Incredibly Kid Friendly Dogs',3),
    ('miniature pinscher','Dog Friendly',2),
    ('miniature pinscher','Amount Of Shedding',2),
    ('miniature pinscher','Size',1),
    ('miniature pinscher','Easy To Train',3),
    ('miniature pinscher','Energy Level',4),
    ('miniature pinscher','Exercise Needs',4),
    ('miniature schnauzer','Adapts Well to Apartment Living',4),
    ('miniature schnauzer','Good For Novice Owners',3),
    ('miniature schnauzer','Sensitivity Level',4),
    ('miniature schnauzer','Tolerates Being Alone',5),
    ('miniature schnauzer','Affectionate with Family',5),
    ('miniature schnauzer','Incredibly Kid Friendly Dogs',3),
    ('miniature schnauzer','Dog Friendly',3),
    ('miniature schnauzer','Amount Of Shedding',2),
    ('miniature schnauzer','Size',2),
    ('miniature schnauzer','Easy To Train',5),
    ('miniature schnauzer','Energy Level',5),
    ('miniature schnauzer','Exercise Needs',5),
    ('mudi','Adapts Well to Apartment Living',2),
    ('mudi','Good For Novice Owners',4),
    ('mudi','Sensitivity Level',4),
    ('mudi','Tolerates Being Alone',2),
    ('mudi','Affectionate with Family',4),
    ('mudi','Incredibly Kid Friendly Dogs',2),
    ('mudi','Dog Friendly',2),
    ('mudi','Amount Of Shedding',3),
    ('mudi','Size',2),
    ('mudi','Easy To Train',5),
    ('mudi','Energy Level',4),
    ('mudi','Exercise Needs',4),
    ('neapolitan mastiff','Adapts Well to Apartment Living',2),
    ('neapolitan mastiff','Good For Novice Owners',1),
    ('neapolitan mastiff','Sensitivity Level',4),
    ('neapolitan mastiff','Tolerates Being Alone',1),
    ('neapolitan mastiff','Affectionate with Family',5),
    ('neapolitan mastiff','Incredibly Kid Friendly Dogs',4),
    ('neapolitan mastiff','Dog Friendly',2),
    ('neapolitan mastiff','Amount Of Shedding',3),
    ('neapolitan mastiff','Size',5),
    ('neapolitan mastiff','Easy To Train',3),
    ('neapolitan mastiff','Energy Level',3),
    ('neapolitan mastiff','Exercise Needs',3),
    ('newfoundland','Adapts Well to Apartment Living',1),
    ('newfoundland','Good For Novice Owners',3),
    ('newfoundland','Sensitivity Level',4),
    ('newfoundland','Tolerates Being Alone',1),
    ('newfoundland','Affectionate with Family',5),
    ('newfoundland','Incredibly Kid Friendly Dogs',5),
    ('newfoundland','Dog Friendly',4),
    ('newfoundland','Amount Of Shedding',5),
    ('newfoundland','Size',5),
    ('newfoundland','Easy To Train',5),
    ('newfoundland','Energy Level',3),
    ('newfoundland','Exercise Needs',3),
    ('norfolk terrier','Adapts Well to Apartment Living',4),
    ('norfolk terrier','Good For Novice Owners',5);
INSERT INTO breeds VALUES
    ('norfolk terrier','Sensitivity Level',4),
    ('norfolk terrier','Tolerates Being Alone',3),
    ('norfolk terrier','Affectionate with Family',5),
    ('norfolk terrier','Incredibly Kid Friendly Dogs',4),
    ('norfolk terrier','Dog Friendly',5),
    ('norfolk terrier','Amount Of Shedding',1),
    ('norfolk terrier','Size',1),
    ('norfolk terrier','Easy To Train',5),
    ('norfolk terrier','Energy Level',4),
    ('norfolk terrier','Exercise Needs',4),
    ('norwegian elkhound','Adapts Well to Apartment Living',4),
    ('norwegian elkhound','Good For Novice Owners',4),
    ('norwegian elkhound','Sensitivity Level',4),
    ('norwegian elkhound','Tolerates Being Alone',2),
    ('norwegian elkhound','Affectionate with Family',5),
    ('norwegian elkhound','Incredibly Kid Friendly Dogs',4),
    ('norwegian elkhound','Dog Friendly',4),
    ('norwegian elkhound','Amount Of Shedding',5),
    ('norwegian elkhound','Size',3),
    ('norwegian elkhound','Easy To Train',2),
    ('norwegian elkhound','Energy Level',5),
    ('norwegian elkhound','Exercise Needs',5),
    ('norwich terrier','Adapts Well to Apartment Living',5),
    ('norwich terrier','Good For Novice Owners',3),
    ('norwich terrier','Sensitivity Level',4),
    ('norwich terrier','Tolerates Being Alone',2),
    ('norwich terrier','Affectionate with Family',5),
    ('norwich terrier','Incredibly Kid Friendly Dogs',5),
    ('norwich terrier','Dog Friendly',5),
    ('norwich terrier','Amount Of Shedding',2),
    ('norwich terrier','Size',1),
    ('norwich terrier','Easy To Train',4),
    ('norwich terrier','Energy Level',5),
    ('norwich terrier','Exercise Needs',4),
    ('old english sheepdog','Adapts Well to Apartment Living',5),
    ('old english sheepdog','Good For Novice Owners',4),
    ('old english sheepdog','Sensitivity Level',4),
    ('old english sheepdog','Tolerates Being Alone',2),
    ('old english sheepdog','Affectionate with Family',5),
    ('old english sheepdog','Incredibly Kid Friendly Dogs',4),
    ('old english sheepdog','Dog Friendly',4),
    ('old english sheepdog','Amount Of Shedding',1),
    ('old english sheepdog','Size',4),
    ('old english sheepdog','Easy To Train',3),
    ('old english sheepdog','Energy Level',4),
    ('old english sheepdog','Exercise Needs',4),
    ('papillon','Adapts Well to Apartment Living',5),
    ('papillon','Good For Novice Owners',5),
    ('papillon','Sensitivity Level',3),
    ('papillon','Tolerates Being Alone',1),
    ('papillon','Affectionate with Family',5),
    ('papillon','Incredibly Kid Friendly Dogs',3),
    ('papillon','Dog Friendly',4),
    ('papillon','Amount Of Shedding',2),
    ('papillon','Size',1),
    ('papillon','Easy To Train',5),
    ('papillon','Energy Level',4),
    ('papillon','Exercise Needs',5),
    ('pekingese','Adapts Well to Apartment Living',5),
    ('pekingese','Good For Novice Owners',4),
    ('pekingese','Sensitivity Level',2),
    ('pekingese','Tolerates Being Alone',3),
    ('pekingese','Affectionate with Family',5),
    ('pekingese','Incredibly Kid Friendly Dogs',2),
    ('pekingese','Dog Friendly',2),
    ('pekingese','Amount Of Shedding',4),
    ('pekingese','Size',1),
    ('pekingese','Easy To Train',3),
    ('pekingese','Energy Level',2),
    ('pekingese','Exercise Needs',2),
    ('pembroke welsh corgi','Adapts Well to Apartment Living',4),
    ('pembroke welsh corgi','Good For Novice Owners',4),
    ('pembroke welsh corgi','Sensitivity Level',4),
    ('pembroke welsh corgi','Tolerates Being Alone',3),
    ('pembroke welsh corgi','Affectionate with Family',5),
    ('pembroke welsh corgi','Incredibly Kid Friendly Dogs',4),
    ('pembroke welsh corgi','Dog Friendly',3),
    ('pembroke welsh corgi','Amount Of Shedding',5),
    ('pembroke welsh corgi','Size',2),
    ('pembroke welsh corgi','Easy To Train',5),
    ('pembroke welsh corgi','Energy Level',4),
    ('pembroke welsh corgi','Exercise Needs',4),
    ('pharaoh hound','Adapts Well to Apartment Living',4),
    ('pharaoh hound','Good For Novice Owners',4),
    ('pharaoh hound','Sensitivity Level',5),
    ('pharaoh hound','Tolerates Being Alone',2),
    ('pharaoh hound','Affectionate with Family',5),
    ('pharaoh hound','Incredibly Kid Friendly Dogs',5),
    ('pharaoh hound','Dog Friendly',5),
    ('pharaoh hound','Amount Of Shedding',2),
    ('pharaoh hound','Size',3),
    ('pharaoh hound','Easy To Train',3),
    ('pharaoh hound','Energy Level',2),
    ('pharaoh hound','Exercise Needs',4),
    ('plott','Adapts Well to Apartment Living',1),
    ('plott','Good For Novice Owners',1),
    ('plott','Sensitivity Level',4),
    ('plott','Tolerates Being Alone',2),
    ('plott','Affectionate with Family',4),
    ('plott','Incredibly Kid Friendly Dogs',3),
    ('plott','Dog Friendly',5),
    ('plott','Amount Of Shedding',2),
    ('plott','Size',3),
    ('plott','Easy To Train',4),
    ('plott','Energy Level',4),
    ('plott','Exercise Needs',5),
    ('pocket beagle','Adapts Well to Apartment Living',4),
    ('pocket beagle','Good For Novice Owners',3),
    ('pocket beagle','Sensitivity Level',4),
    ('pocket beagle','Tolerates Being Alone',2),
    ('pocket beagle','Affectionate with Family',5),
    ('pocket beagle','Incredibly Kid Friendly Dogs',5),
    ('pocket beagle','Dog Friendly',5),
    ('pocket beagle','Amount Of Shedding',3),
    ('pocket beagle','Size',2),
    ('pocket beagle','Easy To Train',3),
    ('pocket beagle','Energy Level',4),
    ('pocket beagle','Exercise Needs',4),
    ('pointer','Adapts Well to Apartment Living',1),
    ('pointer','Good For Novice Owners',1),
    ('pointer','Sensitivity Level',3),
    ('pointer','Tolerates Being Alone',1),
    ('pointer','Affectionate with Family',5),
    ('pointer','Incredibly Kid Friendly Dogs',5),
    ('pointer','Dog Friendly',5),
    ('pointer','Amount Of Shedding',3),
    ('pointer','Size',3),
    ('pointer','Easy To Train',5),
    ('pointer','Energy Level',5),
    ('pointer','Exercise Needs',5),
    ('pomeranian','Adapts Well to Apartment Living',4),
    ('pomeranian','Good For Novice Owners',4),
    ('pomeranian','Sensitivity Level',4),
    ('pomeranian','Tolerates Being Alone',1),
    ('pomeranian','Affectionate with Family',5),
    ('pomeranian','Incredibly Kid Friendly Dogs',2),
    ('pomeranian','Dog Friendly',2),
    ('pomeranian','Amount Of Shedding',4),
    ('pomeranian','Size',1),
    ('pomeranian','Easy To Train',4),
    ('pomeranian','Energy Level',3),
    ('pomeranian','Exercise Needs',2),
    ('pomsky','Adapts Well to Apartment Living',5),
    ('pomsky','Good For Novice Owners',2),
    ('pomsky','Sensitivity Level',4),
    ('pomsky','Tolerates Being Alone',1),
    ('pomsky','Affectionate with Family',5),
    ('pomsky','Incredibly Kid Friendly Dogs',2),
    ('pomsky','Dog Friendly',3),
    ('pomsky','Amount Of Shedding',4),
    ('pomsky','Size',2),
    ('pomsky','Easy To Train',3),
    ('pomsky','Energy Level',4),
    ('pomsky','Exercise Needs',3),
    ('poodle','Adapts Well to Apartment Living',5),
    ('poodle','Good For Novice Owners',5),
    ('poodle','Sensitivity Level',4),
    ('poodle','Tolerates Being Alone',1),
    ('poodle','Affectionate with Family',5),
    ('poodle','Incredibly Kid Friendly Dogs',5),
    ('poodle','Dog Friendly',4),
    ('poodle','Amount Of Shedding',1),
    ('poodle','Size',4),
    ('poodle','Easy To Train',5),
    ('poodle','Energy Level',4),
    ('poodle','Exercise Needs',4),
    ('pug','Adapts Well to Apartment Living',5),
    ('pug','Good For Novice Owners',5),
    ('pug','Sensitivity Level',3),
    ('pug','Tolerates Being Alone',1),
    ('pug','Affectionate with Family',5),
    ('pug','Incredibly Kid Friendly Dogs',4),
    ('pug','Dog Friendly',4),
    ('pug','Amount Of Shedding',5),
    ('pug','Size',2),
    ('pug','Easy To Train',3),
    ('pug','Energy Level',3),
    ('pug','Exercise Needs',3),
    ('puggle','Adapts Well to Apartment Living',4),
    ('puggle','Good For Novice Owners',5),
    ('puggle','Sensitivity Level',3),
    ('puggle','Tolerates Being Alone',3),
    ('puggle','Affectionate with Family',3),
    ('puggle','Incredibly Kid Friendly Dogs',5),
    ('puggle','Dog Friendly',5),
    ('puggle','Amount Of Shedding',3),
    ('puggle','Size',2),
    ('puggle','Easy To Train',2),
    ('puggle','Energy Level',3),
    ('puggle','Exercise Needs',3),
    ('rat terrier','Adapts Well to Apartment Living',5),
    ('rat terrier','Good For Novice Owners',3),
    ('rat terrier','Sensitivity Level',4),
    ('rat terrier','Tolerates Being Alone',3),
    ('rat terrier','Affectionate with Family',4),
    ('rat terrier','Incredibly Kid Friendly Dogs',5),
    ('rat terrier','Dog Friendly',3),
    ('rat terrier','Amount Of Shedding',4),
    ('rat terrier','Size',1),
    ('rat terrier','Easy To Train',5),
    ('rat terrier','Energy Level',5),
    ('rat terrier','Exercise Needs',4),
    ('redbone coonhound','Adapts Well to Apartment Living',4),
    ('redbone coonhound','Good For Novice Owners',2),
    ('redbone coonhound','Sensitivity Level',5),
    ('redbone coonhound','Tolerates Being Alone',2),
    ('redbone coonhound','Affectionate with Family',5),
    ('redbone coonhound','Incredibly Kid Friendly Dogs',5),
    ('redbone coonhound','Dog Friendly',4),
    ('redbone coonhound','Amount Of Shedding',2),
    ('redbone coonhound','Size',3),
    ('redbone coonhound','Easy To Train',3),
    ('redbone coonhound','Energy Level',4),
    ('redbone coonhound','Exercise Needs',5),
    ('rhodesian ridgeback','Adapts Well to Apartment Living',1),
    ('rhodesian ridgeback','Good For Novice Owners',2),
    ('rhodesian ridgeback','Sensitivity Level',4),
    ('rhodesian ridgeback','Tolerates Being Alone',2),
    ('rhodesian ridgeback','Affectionate with Family',5),
    ('rhodesian ridgeback','Incredibly Kid Friendly Dogs',4),
    ('rhodesian ridgeback','Dog Friendly',4),
    ('rhodesian ridgeback','Amount Of Shedding',4),
    ('rhodesian ridgeback','Size',4),
    ('rhodesian ridgeback','Easy To Train',2),
    ('rhodesian ridgeback','Energy Level',4),
    ('rhodesian ridgeback','Exercise Needs',5),
    ('rottweiler','Adapts Well to Apartment Living',2),
    ('rottweiler','Good For Novice Owners',1),
    ('rottweiler','Sensitivity Level',4),
    ('rottweiler','Tolerates Being Alone',1),
    ('rottweiler','Affectionate with Family',5),
    ('rottweiler','Incredibly Kid Friendly Dogs',4),
    ('rottweiler','Dog Friendly',2),
    ('rottweiler','Amount Of Shedding',4),
    ('rottweiler','Size',3),
    ('rottweiler','Easy To Train',4),
    ('rottweiler','Energy Level',4),
    ('rottweiler','Exercise Needs',4),
    ('saint bernard','Adapts Well to Apartment Living',3),
    ('saint bernard','Good For Novice Owners',2),
    ('saint bernard','Sensitivity Level',4),
    ('saint bernard','Tolerates Being Alone',1),
    ('saint bernard','Affectionate with Family',5),
    ('saint bernard','Incredibly Kid Friendly Dogs',5),
    ('saint bernard','Dog Friendly',5),
    ('saint bernard','Amount Of Shedding',4),
    ('saint bernard','Size',5),
    ('saint bernard','Easy To Train',2),
    ('saint bernard','Energy Level',3),
    ('saint bernard','Exercise Needs',2);
INSERT INTO breeds VALUES
    ('saluki','Adapts Well to Apartment Living',1),
    ('saluki','Good For Novice Owners',2),
    ('saluki','Sensitivity Level',5),
    ('saluki','Tolerates Being Alone',1),
    ('saluki','Affectionate with Family',5),
    ('saluki','Incredibly Kid Friendly Dogs',4),
    ('saluki','Dog Friendly',4),
    ('saluki','Amount Of Shedding',2),
    ('saluki','Size',4),
    ('saluki','Easy To Train',4),
    ('saluki','Energy Level',5),
    ('saluki','Exercise Needs',5),
    ('schipperke','Adapts Well to Apartment Living',4),
    ('schipperke','Good For Novice Owners',4),
    ('schipperke','Sensitivity Level',4),
    ('schipperke','Tolerates Being Alone',3),
    ('schipperke','Affectionate with Family',4),
    ('schipperke','Incredibly Kid Friendly Dogs',5),
    ('schipperke','Dog Friendly',2),
    ('schipperke','Amount Of Shedding',3),
    ('schipperke','Size',1),
    ('schipperke','Easy To Train',2),
    ('schipperke','Energy Level',5),
    ('schipperke','Exercise Needs',5),
    ('scottish terrier','Adapts Well to Apartment Living',4),
    ('scottish terrier','Good For Novice Owners',2),
    ('scottish terrier','Sensitivity Level',4),
    ('scottish terrier','Tolerates Being Alone',3),
    ('scottish terrier','Affectionate with Family',5),
    ('scottish terrier','Incredibly Kid Friendly Dogs',4),
    ('scottish terrier','Dog Friendly',4),
    ('scottish terrier','Amount Of Shedding',2),
    ('scottish terrier','Size',2),
    ('scottish terrier','Easy To Train',1),
    ('scottish terrier','Energy Level',4),
    ('scottish terrier','Exercise Needs',4),
    ('shetland sheepdog','Adapts Well to Apartment Living',2),
    ('shetland sheepdog','Good For Novice Owners',3),
    ('shetland sheepdog','Sensitivity Level',5),
    ('shetland sheepdog','Tolerates Being Alone',2),
    ('shetland sheepdog','Affectionate with Family',5),
    ('shetland sheepdog','Incredibly Kid Friendly Dogs',5),
    ('shetland sheepdog','Dog Friendly',4),
    ('shetland sheepdog','Amount Of Shedding',5),
    ('shetland sheepdog','Size',1),
    ('shetland sheepdog','Easy To Train',5),
    ('shetland sheepdog','Energy Level',4),
    ('shetland sheepdog','Exercise Needs',4),
    ('shiba inu','Adapts Well to Apartment Living',5),
    ('shiba inu','Good For Novice Owners',4),
    ('shiba inu','Sensitivity Level',3),
    ('shiba inu','Tolerates Being Alone',5),
    ('shiba inu','Affectionate with Family',4),
    ('shiba inu','Incredibly Kid Friendly Dogs',3),
    ('shiba inu','Dog Friendly',3),
    ('shiba inu','Amount Of Shedding',4),
    ('shiba inu','Size',2),
    ('shiba inu','Easy To Train',2),
    ('shiba inu','Energy Level',4),
    ('shiba inu','Exercise Needs',3),
    ('shih tzu','Adapts Well to Apartment Living',5),
    ('shih tzu','Good For Novice Owners',5),
    ('shih tzu','Sensitivity Level',3),
    ('shih tzu','Tolerates Being Alone',3),
    ('shih tzu','Affectionate with Family',5),
    ('shih tzu','Incredibly Kid Friendly Dogs',4),
    ('shih tzu','Dog Friendly',4),
    ('shih tzu','Amount Of Shedding',3),
    ('shih tzu','Size',1),
    ('shih tzu','Easy To Train',3),
    ('shih tzu','Energy Level',2),
    ('shih tzu','Exercise Needs',2),
    ('siberian husky','Adapts Well to Apartment Living',2),
    ('siberian husky','Good For Novice Owners',1),
    ('siberian husky','Sensitivity Level',4),
    ('siberian husky','Tolerates Being Alone',1),
    ('siberian husky','Affectionate with Family',5),
    ('siberian husky','Incredibly Kid Friendly Dogs',5),
    ('siberian husky','Dog Friendly',5),
    ('siberian husky','Amount Of Shedding',3),
    ('siberian husky','Size',3),
    ('siberian husky','Easy To Train',2),
    ('siberian husky','Energy Level',5),
    ('siberian husky','Exercise Needs',5),
    ('silky terrier','Adapts Well to Apartment Living',5),
    ('silky terrier','Good For Novice Owners',3),
    ('silky terrier','Sensitivity Level',3),
    ('silky terrier','Tolerates Being Alone',3),
    ('silky terrier','Affectionate with Family',4),
    ('silky terrier','Incredibly Kid Friendly Dogs',3),
    ('silky terrier','Dog Friendly',2),
    ('silky terrier','Amount Of Shedding',2),
    ('silky terrier','Size',1),
    ('silky terrier','Easy To Train',4),
    ('silky terrier','Energy Level',4),
    ('silky terrier','Exercise Needs',3),
    ('staffordshire bull terrier','Adapts Well to Apartment Living',3),
    ('staffordshire bull terrier','Good For Novice Owners',1),
    ('staffordshire bull terrier','Sensitivity Level',4),
    ('staffordshire bull terrier','Tolerates Being Alone',2),
    ('staffordshire bull terrier','Affectionate with Family',5),
    ('staffordshire bull terrier','Incredibly Kid Friendly Dogs',5),
    ('staffordshire bull terrier','Dog Friendly',1),
    ('staffordshire bull terrier','Amount Of Shedding',3),
    ('staffordshire bull terrier','Size',2),
    ('staffordshire bull terrier','Easy To Train',2),
    ('staffordshire bull terrier','Energy Level',3),
    ('staffordshire bull terrier','Exercise Needs',4),
    ('standard schnauzer','Adapts Well to Apartment Living',4),
    ('standard schnauzer','Good For Novice Owners',2),
    ('standard schnauzer','Sensitivity Level',4),
    ('standard schnauzer','Tolerates Being Alone',2),
    ('standard schnauzer','Affectionate with Family',4),
    ('standard schnauzer','Incredibly Kid Friendly Dogs',4),
    ('standard schnauzer','Dog Friendly',3),
    ('standard schnauzer','Amount Of Shedding',1),
    ('standard schnauzer','Size',3),
    ('standard schnauzer','Easy To Train',3),
    ('standard schnauzer','Energy Level',5),
    ('standard schnauzer','Exercise Needs',5),
    ('tibetan mastiff','Adapts Well to Apartment Living',1),
    ('tibetan mastiff','Good For Novice Owners',1),
    ('tibetan mastiff','Sensitivity Level',5),
    ('tibetan mastiff','Tolerates Being Alone',1),
    ('tibetan mastiff','Affectionate with Family',5),
    ('tibetan mastiff','Incredibly Kid Friendly Dogs',5),
    ('tibetan mastiff','Dog Friendly',5),
    ('tibetan mastiff','Amount Of Shedding',2),
    ('tibetan mastiff','Size',5),
    ('tibetan mastiff','Easy To Train',1),
    ('tibetan mastiff','Energy Level',4),
    ('tibetan mastiff','Exercise Needs',2),
    ('tibetan spaniel','Adapts Well to Apartment Living',5),
    ('tibetan spaniel','Good For Novice Owners',4),
    ('tibetan spaniel','Sensitivity Level',5),
    ('tibetan spaniel','Tolerates Being Alone',1),
    ('tibetan spaniel','Affectionate with Family',5),
    ('tibetan spaniel','Incredibly Kid Friendly Dogs',5),
    ('tibetan spaniel','Dog Friendly',4),
    ('tibetan spaniel','Amount Of Shedding',3),
    ('tibetan spaniel','Size',1),
    ('tibetan spaniel','Easy To Train',4),
    ('tibetan spaniel','Energy Level',3),
    ('tibetan spaniel','Exercise Needs',4),
    ('tibetan terrier','Adapts Well to Apartment Living',5),
    ('tibetan terrier','Good For Novice Owners',3),
    ('tibetan terrier','Sensitivity Level',4),
    ('tibetan terrier','Tolerates Being Alone',1),
    ('tibetan terrier','Affectionate with Family',5),
    ('tibetan terrier','Incredibly Kid Friendly Dogs',5),
    ('tibetan terrier','Dog Friendly',4),
    ('tibetan terrier','Amount Of Shedding',1),
    ('tibetan terrier','Size',2),
    ('tibetan terrier','Easy To Train',4),
    ('tibetan terrier','Energy Level',5),
    ('tibetan terrier','Exercise Needs',5),
    ('toy fox terrier','Adapts Well to Apartment Living',5),
    ('toy fox terrier','Good For Novice Owners',3),
    ('toy fox terrier','Sensitivity Level',4),
    ('toy fox terrier','Tolerates Being Alone',1),
    ('toy fox terrier','Affectionate with Family',5),
    ('toy fox terrier','Incredibly Kid Friendly Dogs',4),
    ('toy fox terrier','Dog Friendly',3),
    ('toy fox terrier','Amount Of Shedding',4),
    ('toy fox terrier','Size',1),
    ('toy fox terrier','Easy To Train',3),
    ('toy fox terrier','Energy Level',5),
    ('toy fox terrier','Exercise Needs',5),
    ('treeing walker coonhound','Adapts Well to Apartment Living',1),
    ('treeing walker coonhound','Good For Novice Owners',2),
    ('treeing walker coonhound','Sensitivity Level',5),
    ('treeing walker coonhound','Tolerates Being Alone',2),
    ('treeing walker coonhound','Affectionate with Family',4),
    ('treeing walker coonhound','Incredibly Kid Friendly Dogs',4),
    ('treeing walker coonhound','Dog Friendly',3),
    ('treeing walker coonhound','Amount Of Shedding',3),
    ('treeing walker coonhound','Size',4),
    ('treeing walker coonhound','Easy To Train',2),
    ('treeing walker coonhound','Energy Level',4),
    ('treeing walker coonhound','Exercise Needs',5),
    ('vizsla','Adapts Well to Apartment Living',1),
    ('vizsla','Good For Novice Owners',3),
    ('vizsla','Sensitivity Level',5),
    ('vizsla','Tolerates Being Alone',1),
    ('vizsla','Affectionate with Family',5),
    ('vizsla','Incredibly Kid Friendly Dogs',5),
    ('vizsla','Dog Friendly',5),
    ('vizsla','Amount Of Shedding',2),
    ('vizsla','Size',3),
    ('vizsla','Easy To Train',5),
    ('vizsla','Energy Level',5),
    ('vizsla','Exercise Needs',5),
    ('weimaraner','Adapts Well to Apartment Living',1),
    ('weimaraner','Good For Novice Owners',2),
    ('weimaraner','Sensitivity Level',5),
    ('weimaraner','Tolerates Being Alone',1),
    ('weimaraner','Affectionate with Family',5),
    ('weimaraner','Incredibly Kid Friendly Dogs',4),
    ('weimaraner','Dog Friendly',3),
    ('weimaraner','Amount Of Shedding',4),
    ('weimaraner','Size',4),
    ('weimaraner','Easy To Train',4),
    ('weimaraner','Energy Level',5),
    ('weimaraner','Exercise Needs',5),
    ('west highland white terrier','Adapts Well to Apartment Living',4),
    ('west highland white terrier','Good For Novice Owners',4),
    ('west highland white terrier','Sensitivity Level',4),
    ('west highland white terrier','Tolerates Being Alone',2),
    ('west highland white terrier','Affectionate with Family',5),
    ('west highland white terrier','Incredibly Kid Friendly Dogs',4),
    ('west highland white terrier','Dog Friendly',5),
    ('west highland white terrier','Amount Of Shedding',4),
    ('west highland white terrier','Size',2),
    ('west highland white terrier','Easy To Train',4),
    ('west highland white terrier','Energy Level',4),
    ('west highland white terrier','Exercise Needs',4),
    ('whippet','Adapts Well to Apartment Living',5),
    ('whippet','Good For Novice Owners',3),
    ('whippet','Sensitivity Level',5),
    ('whippet','Tolerates Being Alone',2),
    ('whippet','Affectionate with Family',5),
    ('whippet','Incredibly Kid Friendly Dogs',5),
    ('whippet','Dog Friendly',4),
    ('whippet','Amount Of Shedding',2),
    ('whippet','Size',3),
    ('whippet','Easy To Train',4),
    ('whippet','Energy Level',5),
    ('whippet','Exercise Needs',5),
    ('yorkipoo','Adapts Well to Apartment Living',5),
    ('yorkipoo','Good For Novice Owners',5),
    ('yorkipoo','Sensitivity Level',4),
    ('yorkipoo','Tolerates Being Alone',3),
    ('yorkipoo','Affectionate with Family',5),
    ('yorkipoo','Incredibly Kid Friendly Dogs',4),
    ('yorkipoo','Dog Friendly',3),
    ('yorkipoo','Amount Of Shedding',1),
    ('yorkipoo','Size',1),
    ('yorkipoo','Easy To Train',4),
    ('yorkipoo','Energy Level',5),
    ('yorkipoo','Exercise Needs',3),
    ('yorkshire terrier','Adapts Well to Apartment Living',5),
    ('yorkshire terrier','Good For Novice Owners',4),
    ('yorkshire terrier','Sensitivity Level',5),
    ('yorkshire terrier','Tolerates Being Alone',2),
    ('yorkshire terrier','Affectionate with Family',4),
    ('yorkshire terrier','Incredibly Kid Friendly Dogs',2),
    ('yorkshire terrier','Dog Friendly',3),
    ('yorkshire terrier','Amount Of Shedding',2),
    ('yorkshire terrier','Size',1),
    ('yorkshire terrier','Easy To Train',3);
INSERT INTO breeds VALUES
    ('yorkshire terrier','Energy Level',5),
    ('yorkshire terrier','Exercise Needs',4),
    ('karelian bear dog','Adapts Well to Apartment Living',2),
    ('karelian bear dog','Good For Novice Owners',1),
    ('karelian bear dog','Sensitivity Level',4),
    ('karelian bear dog','Tolerates Being Alone',2),
    ('karelian bear dog','Affectionate with Family',4),
    ('karelian bear dog','Incredibly Kid Friendly Dogs',3),
    ('karelian bear dog','Dog Friendly',1),
    ('karelian bear dog','Amount Of Shedding',3),
    ('karelian bear dog','Size',3),
    ('karelian bear dog','Easy To Train',2),
    ('karelian bear dog','Energy Level',4),
    ('karelian bear dog','Exercise Needs',4),
    ('karelian bear dog','Adapts Well to Apartment Living',2),
    ('karelian bear dog','Good For Novice Owners',1),
    ('karelian bear dog','Sensitivity Level',4),
    ('karelian bear dog','Tolerates Being Alone',2),
    ('karelian bear dog','Affectionate with Family',4),
    ('karelian bear dog','Incredibly Kid Friendly Dogs',3),
    ('karelian bear dog','Dog Friendly',1),
    ('karelian bear dog','Amount Of Shedding',3),
    ('karelian bear dog','Size',3),
    ('karelian bear dog','Easy To Train',2),
    ('karelian bear dog','Energy Level',4),
    ('karelian bear dog','Exercise Needs',4),
    ('karelian bear dog','Adapts Well to Apartment Living',2),
    ('karelian bear dog','Good For Novice Owners',1),
    ('karelian bear dog','Sensitivity Level',4),
    ('karelian bear dog','Tolerates Being Alone',2),
    ('karelian bear dog','Affectionate with Family',4),
    ('karelian bear dog','Incredibly Kid Friendly Dogs',3),
    ('karelian bear dog','Dog Friendly',1),
    ('karelian bear dog','Amount Of Shedding',3),
    ('karelian bear dog','Size',3),
    ('karelian bear dog','Easy To Train',2),
    ('karelian bear dog','Energy Level',4),
    ('karelian bear dog','Exercise Needs',4),
    ('dutch shepherd','Adapts Well to Apartment Living',3),
    ('dutch shepherd','Good For Novice Owners',3),
    ('dutch shepherd','Sensitivity Level',3),
    ('dutch shepherd','Tolerates Being Alone',2),
    ('dutch shepherd','Affectionate with Family',4),
    ('dutch shepherd','Incredibly Kid Friendly Dogs',4),
    ('dutch shepherd','Dog Friendly',4),
    ('dutch shepherd','Amount Of Shedding',4),
    ('dutch shepherd','Size',3),
    ('dutch shepherd','Easy To Train',5),
    ('dutch shepherd','Energy Level',4),
    ('dutch shepherd','Exercise Needs',4),
    ('dutch shepherd','Adapts Well to Apartment Living',3),
    ('dutch shepherd','Good For Novice Owners',3),
    ('dutch shepherd','Sensitivity Level',3),
    ('dutch shepherd','Tolerates Being Alone',2),
    ('dutch shepherd','Affectionate with Family',4),
    ('dutch shepherd','Incredibly Kid Friendly Dogs',4),
    ('dutch shepherd','Dog Friendly',4),
    ('dutch shepherd','Amount Of Shedding',4),
    ('dutch shepherd','Size',3),
    ('dutch shepherd','Easy To Train',5),
    ('dutch shepherd','Energy Level',4),
    ('dutch shepherd','Exercise Needs',4),
    ('dutch shepherd','Adapts Well to Apartment Living',3),
    ('dutch shepherd','Good For Novice Owners',3),
    ('dutch shepherd','Sensitivity Level',3),
    ('dutch shepherd','Tolerates Being Alone',2),
    ('dutch shepherd','Affectionate with Family',4),
    ('dutch shepherd','Incredibly Kid Friendly Dogs',4),
    ('dutch shepherd','Dog Friendly',4),
    ('dutch shepherd','Amount Of Shedding',4),
    ('dutch shepherd','Size',3),
    ('dutch shepherd','Easy To Train',5),
    ('dutch shepherd','Energy Level',4),
    ('dutch shepherd','Exercise Needs',4);
        